baseurl = "https://trolddom.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Trolddom"
    subtitle = ""
    keywords = ""
    copyright = "(C) 2024 Rasmus Neckelmann"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Trolddom"
      logoHomeLink = "/"
	  
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Blog"
        name = "Blog"
        url = "https://plantbasedgames.io/blog/"
		
	  [[languages.en.menu.main]]
		identifier = "Discord"
		name = "Discord"
		url = "https://discord.gg/w2HvMHeq24"
		
	  [[languages.en.menu.main]]
	    identifier = "BuyMeACoffee"
		name = "Buy Me A Coffee"
		url = "https://buymeacoffee.com/demogorgon1"

